Places "ubuntu-desktop-installer" as a variable
For brevity due repetition.

diff --git a/wsl-setup b/wsl-setup
--- a/wsl-setup
+++ b/wsl-setup
@@ -34,9 +34,10 @@ function mount_snaps() {
     done
 }
 
+UDI="ubuntu-desktop-installer"
 snap_core=$(ls -1 /var/lib/snapd/snaps/core20_*.snap||true|sort -n -t_ -k2|tail -1)
 snap_theme=$(ls -1 /var/lib/snapd/snaps/gtk-common-themes_*.snap||true|sort -n -t_ -k2|tail -1)
-snap_udi=$(ls -1 /var/lib/snapd/snaps/ubuntu-desktop-installer_*.snap||true|sort -n -t_ -k2|tail -1)
+snap_udi=$(ls -1 /var/lib/snapd/snaps/"${UDI}"_*.snap||true|sort -n -t_ -k2|tail -1)
 snap_subiquity=$(ls -1 /var/lib/snapd/snaps/subiquity_*.snap||true|sort -n -t_ -k2|tail -1)
 
 if [ -z "${snap_core}" ]; then
@@ -44,10 +45,10 @@ if [ -z "${snap_core}" ]; then
     exit 1
 elif [ -z "${snap_subiquity}" ]; then
     if [ -z "${snap_udi}" ]; then
-        echo "E: Could not find either ubuntu-desktop-installer or subiquity snaps"
+        echo "E: Could not find either ${UDI} or subiquity snaps"
         exit 1
     elif [ -z "${snap_theme}" ]; then
-        echo "E: Could not find gtk-common-themes snap required by the ubuntu-desktop-installer."
+        echo "E: Could not find gtk-common-themes snap required by the ${UDI}."
         exit 1
     fi
 fi
@@ -55,7 +56,7 @@ fi
 #############################################
 # Setup our mock snap environment variables #
 #############################################
-snap_name="ubuntu-desktop-installer"
+snap_name="${UDI}"
 snap_wslsetup="${snap_udi}"
 # Unlikely that both will coexist, but if so, Subiquity would have been added
 # later to the rootfs, thus being the modern choice it should have preference.
@@ -94,7 +95,7 @@ export XDG_RUNTIME_DIR="/run/user/${SUDO_UID}"
 export SNAP_CORE_DIR="/snap/core20/current"
 
 # Mount theme snap inside the UDI snap
-if [[ "${snap_name}" == "ubuntu-desktop-installer" ]]; then
+if [[ "${snap_name}" == "${UDI}" ]]; then
     if ! grep -qs " $(readlink -f $SNAP)/data-dir " /proc/mounts; then
         mount -o bind /snap/gtk-common-themes/current/share $SNAP/data-dir
     fi
